---
apiVersion: batch/v1
kind: Job
metadata:
  name: livess-mongo
 
spec:
  template:
    metadata:
      name: liveness
   
    spec:
      restartPolicy: Never
      containers:
      - name: liveness
        image: ranjnshashank855/py-server:test
        imagePullPolicy: Always

        env: 

            # Time period (in sec) b/w retries for DB init check
          - name: INIT_WAIT_DELAY
            value: "30"
    
            # No of retries for DB init check 
          - name: INIT_RETRY_COUNT
            value: "10"
    
            # Time period (in sec) b/w liveness checks
          - name: LIVENESS_PERIOD_SECONDS
            value: "10"
    
            # Time period (in sec) b/w retries for db_connect failure
          - name: LIVENESS_TIMEOUT_SECONDS
            value: "10"
    
            # No of retries after a db_connect failure before declaring liveness fail
          - name: LIVENESS_RETRY_COUNT
            value: "6"
              
 
        command: ["/bin/bash"]
        args: ["-c", "python ./server.py ; exit 0"]
